# Protocol Buffers - Google's data interchange format
# Copyright 2024 Google LLC.  All rights reserved.

# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

[package]
name = "protobuf"
version = "4.27.3-beta.0"
edition = "2021"
links = "libupb"
license = "BSD-3-Clause"
rust-version = "1.74"

[lib]
path = "src/shared.rs"

[dependencies]
paste = "1.0.15"

[dev-dependencies]
googletest = {git = "https://github.com/google/googletest-rust.git" }

[build-dependencies]
cc = "1.1.6"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(bzl)', 'cfg(cpp_kernel)', 'cfg(upb_kernel)'] }