[package]
edition = "2021"   # The Rust edition (not to be confused with Protobuf Edition).
name = "protobuf-codegen"
readme = "README.md"
version = "{VERSION}"
description = "Code generator for Rust Protocol Buffers bindings"
license = "BSD-3-Clause"
rust-version = "1.74"


[dependencies]
walkdir = "2.5.0"
cc = "1.1.6"