name: Run a Docker/Bazel workflow

on:
  workflow_call:
    inputs:
      name:
        required: True
        description: "The name to display for the test"
        type: string
      targets:
        required: true
        description: "The targets to test."
        type: string
      image:
        required: false
        default: 'us-docker.pkg.dev/protobuf-build/containers/common/linux/bazel:5.1.1-aec4d74f2eb6938fc53ef7d9a79a4bf2da24abc1'
        description: "The docker image to use."
        type: string
      flags:
        required: false
        default: ''
        description: "Extra flags to pass to Bazel."
        type: string
      cache:
        required: true
        description: "A unique path for where to store the bazel cache."
        type: string
    secrets:
      GAR_SERVICE_ACCOUNT:
        required: true

run-name: ${{ inputs.name }}

jobs:
  run:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          export_environment_variables: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Use gcloud CLI
        run: gcloud info
      - name: Configure Docker
        run: gcloud auth configure-docker -q us-docker.pkg.dev

      - name: Set up Bazel caching
        run: >
          echo "BAZEL_CACHE=
          --google_credentials=/workspace/$(basename $GOOGLE_APPLICATION_CREDENTIALS)
          --remote_upload_local_results
          --remote_cache=https://storage.googleapis.com/protobuf-bazel-cache/protobuf/gha/${{ inputs.cache }}" >> $GITHUB_ENV
        if: ${{ inputs.cache }}

      - name: Pull Docker Image
        run: docker pull ${{ inputs.image }}
      - name: Test
        run: >
          docker run -v${{ github.workspace }}:/workspace ${{ inputs.image }}
          test --keep_going --test_output=errors $BAZEL_CACHE
          ${{ inputs.flags }} ${{ inputs.targets }}
