name: Python Bazel

on:
  workflow_call:
    inputs:
      checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string

jobs:
  run:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        type: [ Pure, C++]
        version: [ "3.7", "3.8", "3.9", "3.10" ]
        include:
          - type: Pure
            targets: //python/... @upb//python/... //python:python_version
          - type: C++
            targets: //python/... //python:python_version
            flags: --define=use_fast_cpp_protos=true
          - type: C++
            version: aarch64
            targets: //python/... //python:aarch64_test
            # TODO(b/262628111) Enable this once conformance tests are fixed.
            flags: --define=use_fast_cpp_protos=true --test_tag_filters=-conformance
            image: us-docker.pkg.dev/protobuf-build/containers/test/linux/emulation:aarch64-e863f8ec6b1dfe41f7dc573bac9c8072a0a68b1b
            emulate: "arm64"

    name: ${{ matrix.type }} ${{ matrix.version }}
    uses: ./.github/workflows/docker_bazel.yml
    with:
      name: ${{ matrix.type }} ${{matrix.version}}
      checkout: ${{ inputs.checkout }}
      image: ${{ matrix.image || format('us-docker.pkg.dev/protobuf-build/containers/test/linux/python:{0}-65526ea124d1034eac33e7c37cc6d65c5bef054f', matrix.version) }}
      flags: ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION
      targets: ${{ matrix.targets }}
      cache: python_bazel/${{ matrix.type }}_${{ matrix.version }}
      emulate: ${{ matrix.emulate }}
    secrets: inherit
